version: 2
jobs:
  build:
    name: Update pod install in readme(s)
    branch: master
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: scripts/update-readme-with-latest-pod-version.sh