version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      branches:
        only:
          - dev
      - checkout
      - run: scripts/update-readme-with-latest-pod-version.sh